[versions]
detekt = "1.20.0"
kotlin = "1.6.21"
ktlintGradle = "10.3.0"
pluginPublish = "0.21.0"
versionCheck = "0.42.0"
sonar = "3.4.0.2513"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
sonar = { id = "org.sonarqube", version.ref = "sonar" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}

[libraries]
junit = "junit:junit:4.13.2"
