name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        experimental: [ false, true, true ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      ## Setup: Repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      ## Setup: Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      ## Setup: GraalVM
      - uses: elide-dev/setup-graalvm@5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            preMerge
            -Pelide.ci=true
            --scan
            --continue

      # Sample run of the plugin
      - name: Run the plugin
        uses: gradle/gradle-build-action@v2
        if: success()
        with:
          arguments: |
            templateExample
            -Pelide.ci=true
            --message="Test Run"
            --tag=CI
            --continue

      # Verify plugin output
      - name: Verify the plugin output
        if: success()
        run: grep -Fxq "[CI] Test Run" ./example/build/template-example.txt
