name: Qodana

on:
  push:
    branches:
      - main
      - stable
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ##
  ## Job: Qodana
  ##
  tools-qodana:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 30
    steps:
      ## Setup: Checkout Code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      ## Run Qodana
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0

      ## Upload SARIF
      - name: 'Upload SARIF Report'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
