name: Sonar

on:
  push:
    branches:
      - main
      - stable
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ##
  ## Job: Sonar
  ##
  tools-sonar:
    runs-on: ubuntu-latest
    steps:
      ## Setup: Checkout Code
      - uses: actions/checkout@v3

      ## Setup: Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      ## Setup: GraalVM
      - uses: elide-tools/setup-graalvm@5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      ## Setup: Checkout Code
      - name: Cache SonarCloud packages
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # tag=v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      ## Prep: Download Caches
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ./build
            ./*/build
            ./*/*/build
          key: elide-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            elide-gradle-${{ runner.os }}
            elide-gradle-

      ## Run Sonar
      - name: "Run Sonar"
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: |
            build
            test
            sonarqube
            --scan
            -Pelide.ci=true
